#!/bin/sh

[ -n "${IPKG_INSTROOT}" ] || {
chmod 755 /etc/init.d/aria2 >/dev/null 2>&1
chmod 755 /etc/init.d/aria2delaystarter >/dev/null 2>&1
/etc/init.d/aria2 enable
/etc/init.d/aria2delaystarter enable
exit 0
}
